### PR TITLE
A new MEOA/D variant

### PR DESCRIPTION
**Pull request by JerryI00**
Hi,

I have submitted the implementation of a new MOEA/D variant. This work has been published in IEEE Transactions of Evolutionary Computation. The basic idea is treat the subproblems and solutions as two sets of agents which have mutual preference to each other. The selection process is therefore a matching process between subproblems and solutions. The corresponding reference is:

K. Li, Q. Zhang, S. Kwong, M. Li and R. Wang, "Stable Matching-Based Selection in Evolutionary Multiobjective Optimization", IEEE Transactions on Evolutionary Computation, 18(6): 909-923, 2014. DOI: 10.1109/TEVC.2013.2293776

If you are satisfied with the codes, please merge it into the jMetal.

Best wishes to you!

Ke

### CODE REVIEW

**Comment by denggaoshan** [comment]
Oh, I have read the paper. 
And by the way,  the function _getName()_ in MOEADSTM.java :
`
	@Override
	public String getName() {
		return "MOEADDRA";
	}
`
Do you mean MOEADSTM?

**Comment by JerryI00** [comment]
Sorry, this is a mistake. It should be MOEADSTM :)

Best wishes to you!

Ke

******************************************
Dr. Ke Li
​Research Fellow
School of Computer Science
The University of Birmingham
Edgbaston, B15 2TT, UK
http://www.cs.bham.ac.uk/~likw
*******************************************

**Comment by Juanjdurillo** [comment]
Dear Ke Li, 

thanks a lot for your contribution. It is great to have the latest advances of MOEA/D implemented in jMetal.

**Comment by ajnebro** [comment]
Dear Ke.
  Thanks for adding a new MOEA/D to jMetal. I have just accepted the pull request.

 I have also added a MOEADSTMRunner.java class to configure and run it.



Antonio

**Comment by ajnebro** [comment]
About the `Quicksort()` method in `MOEADUtils, I don't see any problem in putting it there given that it used only by the MOEADSTM algorithm. The only point is that I have made a small refactoring to name it `quickSort()`.

It is true that that method could be generalized, but this is a minor issue. The big issue that we have to face is that now we have a number of algorithms (MOEA/D variants, MOMBI and MOMBI2, WASFGA and GWASFGA) based on scalarizing approaches with weights and all of them implement the same abstractions in their own.

**Comment by JerryI00** [comment]
Dear Antonio,

Thanks for your help. I am glad to contribute to the jMetal project which I have been with it for a couple of years.

Cheers,

Ke

******************************************
Dr. Ke Li
​Research Fellow
School of Computer Science
The University of Birmingham
Edgbaston, B15 2TT, UK
http://www.cs.bham.ac.uk/~likw
*******************************************

**Comment by matthieu-vergne** [comment]
What about making a general class of weighting strategy? With a general interface and few specific implementations that you can reuse in the corresponding algorithms.

If you think it is useful to discuss it further, we can open a dedicated issue.

**Comment by JerryI00** [comment]
What do you mean by weighting strategy? Do you mean the generation of weight vectors which are used in decomposition-based methods (e.g., MOEA/D variants, MOMBI and MOMBI2, WASFGA and GWASFGA)?

******************************************
Dr. Ke Li
​Research Fellow
School of Computer Science
The University of Birmingham
Edgbaston, B15 2TT, UK
http://www.cs.bham.ac.uk/~likw
*******************************************

**Comment by ajnebro** [comment]
Yes. If we take a look to these algorithms we find:
* MOEA/D (and variants): 
 * Three aggregation schemes (TCHE, PBI, AGG) implemented in the `fitnessFunction()` method in class `AbstractMOEAD`
 * A method `initializeUniformWeight()` to compute/read the weights
* MOMBI/MOMBI2:
 * An abstract class `AbstractUtilityFunctionsSet` with methods `evaluate()` and `loadWeightsFromFile()`
 * Two subclasses of AbstractUtilityFunctionsSet: `ASFUtilityFunctionSet` and `TchebycheffUtilityFunctionsSet`
* WASFGA/GWASFGA:
 * A `WeightVector` class with methods such as `initUniformWeights2D()` and `getWeightsFromFile()`.

**Comment by matthieu-vergne** [comment]
Yep, `AbstractMOEAD.fitnessFunction(...)` has the typical pattern of common concepts (fitness and individual, lambda I am less sure), leading to have at least a common interface, and each `if` case would provide a different implementation. `AbstractUtilityFunctionsSet` and its implementations are an example which could be further generalized. That would be the idea. I even wonder if the initialization and evaluation should not be kept independent somehow.

Probably a dedicated issue would be worth, indeed.

**Comment by JerryI00** [comment]
Yes, I agree with your point. Initializing the weight vectors by reading from external data files is not a good idea indeed. I can try to implement a JAVA version of weight vector generation method which is derived from my current MATLAB version.

******************************************
Dr. Ke Li
​Research Fellow
School of Computer Science
The University of Birmingham
Edgbaston, B15 2TT, UK
http://www.cs.bham.ac.uk/~likw
*******************************************

**Comment by matthieu-vergne** [comment]
This is a general point, not only for your code. So I opened the issue #133 to have a dedicated place.

**Pull request merged**
