### PR TITLE
Add DescribedEntity to factor name and description.

### PR DESCRIPTION
**Pull request by matthieu-vergne**

### CODE REVIEW

**Comment by ajnebro** [comment]
Thanks :). Now everything compiles fine.

**Comment by matthieu-vergne** [comment]
Don't hesitate to use `DescribedEntity` and `SimpleDescribedEntity` for factoring existing stuff, like algorithms name/description and stuff like that (if there is).

**Comment by ajnebro** [comment]
Sure, I will make us of them. The only point is that I would use as package name something like "naming" or "description" instead of "generic".

**Comment by matthieu-vergne** [comment]
Sure, just move the stuff. Even for the measures, considering that it is central for the genericity of the algorithms, it should not be in "util". There is some reorganization to do their.

**Pull request merged**
